// auto-generated

import type { Manifest } from '@jk2908/drift'

export const manifest = {
	'/': {
		__id: '$P2477003153798501763',
		__path: '/',
		__params: [],
		__kind: '$P',
		method: 'get',
		paths: {
			shell: 'app/+layout.tsx',
			layouts: [],
			error: null,
		},
		shouldPrerender: false,
		isDynamic: false,
		isCatchAll: false,
	},
	'/about': {
		__id: '$P13230934839206242355',
		__path: '/about',
		__params: [],
		__kind: '$P',
		method: 'get',
		paths: {
			shell: 'app/+layout.tsx',
			layouts: ['app/about/+layout.tsx'],
			error: null,
		},
		shouldPrerender: false,
		isDynamic: false,
		isCatchAll: false,
	},
	'/about/another': {
		__id: '$P14097920357031786620',
		__path: '/about/another',
		__params: [],
		__kind: '$P',
		method: 'get',
		paths: {
			shell: 'app/+layout.tsx',
			layouts: ['app/about/+layout.tsx'],
			error: 'app/about/another/+error.tsx',
		},
		shouldPrerender: false,
		isDynamic: false,
		isCatchAll: false,
	},
	'/about/me': {
		__id: '$P17625360362423944836',
		__path: '/about/me',
		__params: [],
		__kind: '$P',
		method: 'get',
		paths: {
			shell: 'app/+layout.tsx',
			layouts: ['app/about/+layout.tsx', 'app/about/me/+layout.tsx'],
			error: null,
		},
		shouldPrerender: false,
		isDynamic: false,
		isCatchAll: false,
	},
	'/foo': {
		__id: '$P12413635232283420789',
		__path: '/foo',
		__params: [],
		__kind: '$P',
		method: 'get',
		paths: {
			shell: 'app/+layout.tsx',
			layouts: [],
			error: null,
		},
		shouldPrerender: false,
		isDynamic: false,
		isCatchAll: false,
	},
	'/p/:id': {
		__id: '$P7251155391163411833',
		__path: '/p/:id',
		__params: ['id'],
		__kind: '$P',
		method: 'get',
		paths: {
			shell: 'app/+layout.tsx',
			layouts: [],
			error: null,
		},
		shouldPrerender: true,
		isDynamic: true,
		isCatchAll: false,
	},
	'/posts': [
		{
			__id: '$P13003434519583876057',
			__path: '/posts',
			__params: [],
			__kind: '$P',
			method: 'get',
			paths: {
				shell: 'app/+layout.tsx',
				layouts: [],
				error: 'app/posts/+error.tsx',
			},
			shouldPrerender: false,
			isDynamic: false,
			isCatchAll: false,
		},
		{
			__id: '$E36045888637312226_get',
			__path: '/posts',
			__params: [],
			__kind: '$E',
			method: 'get',
		},
		{
			__id: '$E36045888637312226_post',
			__path: '/posts',
			__params: [],
			__kind: '$E',
			method: 'post',
		},
	],
	'/test/*': {
		__id: '$P10194420604043210043',
		__path: '/test/*',
		__params: ['catch'],
		__kind: '$P',
		method: 'get',
		paths: {
			shell: 'app/+layout.tsx',
			layouts: [],
			error: null,
		},
		shouldPrerender: false,
		isDynamic: false,
		isCatchAll: true,
	},
} as const satisfies Manifest
