import { describe, expect, it } from 'vitest'

import { format } from '../../../../src/internal/codegen/format.js'

describe('codegen/format', () => {
	it('formats generated source with repo conventions', async () => {
		const result = await format(
			'entry.rsc.tsx',
			'import { createHandler } from "@jk2908/solas/env/rsc"\n\nconst x={a:1};\n\nexport default createHandler(x)',
		)

		expect(result).toContain("import { createHandler } from '@jk2908/solas/env/rsc'")
		expect(result).toContain('const x = { a: 1 }')
		expect(result).not.toContain(';')
	})

	it('formats tsx entry output', async () => {
		const content = [
			'// auto-generated by Solas',
			'',
			"import { browser } from '@jk2908/solas/env/browser'",
			'',
			'browser()',
			'',
		].join('\n')

		const result = await format('entry.browser.tsx', content)
		expect(result).toMatch(
			/^\/\/ auto-generated by Solas\n\nimport \{ browser \} from '@jk2908\/solas\/env\/browser'\n\nbrowser\(\)\n$/,
		)
	})

	it('returns original content when parsing fails', async () => {
		const content = 'const x = '
		const result = await format('broken.ts', content)
		expect(result).toBe(content)
	})
})
